create table student (
    ID BIGINT PRIMARY KEY,
    FIRST_NAME VARCHAR2,
    LAST_NAME VARCHAR2,
    CREDIT_RATING INT
);

create table course (
    ID BIGINT PRIMARY KEY,
    COURSE_NAME VARCHAR2,
    DESCRIPTION VARCHAR2,
    CLASS_SIZE_LIMIT INT
);

create table course_prerequisite (
    ID BIGINT PRIMARY KEY,
    COURSE_ID BIGINT,
    PREREQ_COURSE_ID BIGINT,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID),
    FOREIGN KEY (PREREQ_COURSE_ID) REFERENCES COURSE(ID)
);

CREATE TABLE ENROLLMENT (
    ID BIGINT PRIMARY KEY,
    STUDENT_ID BIGINT,
    COURSE_ID BIGINT,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);